name: crewai-workshop

services:
  crewai:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - phoenix
      - dind
    volumes:
      - ./${DYNAMIC_DEMO_FOLDER}/run.py:/app/run.py
      - ./${DYNAMIC_DEMO_FOLDER}/src:/app/src/
      - ./${DYNAMIC_DEMO_FOLDER}/knowledge:/app/knowledge
      - ./${DYNAMIC_DEMO_FOLDER}/memory:/app/memory
      - ./shared/:/app/src/shared/
    networks:
      - default

  phoenix:
    image: arizephoenix/phoenix:version-12.4.0
    env_file: .env
    ports:
      - "6006:6006"
    depends_on:
      - phoenix-db
    networks:
      - default

  phoenix-db:
    image: "postgres:16.4-alpine"
    env_file: .env
    volumes:
      - phoenix-data:/var/lib/postgresql/data
    networks:
      - default

  dind:
    image: docker:28.5.1-dind-alpine3.22
    command: --host=tcp://0.0.0.0:2375
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=   # Disable TLS
    networks:
      - default

volumes:
  phoenix-data:

networks:
  default:
